# metrics to present on hparams table used for test results

metrics:
  test_loss: 0
  test_kl_mean: 0
  test_mean_negative_log_likelihood: 0
  test_ACC: 0
  test_BALACC: 0
  test_RECALL: 0
  test_PRECISION: 0
  test_AUROC: 0
  test_AUPRC: 0

optimize: test_AUROC