optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.005

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.5
  patience: 50
  mode: ${callbacks.early_stopping.mode}
  threshold: 0.00001
  cooldown: 0
  min_lr: 1e-5

# vib
num_classes: -1
alpha: -1
beta: 0.01
num_samples: 1
class_weight_file:
monitor_metric: ${callbacks.early_stopping.monitor} # for the scheduler
use_class_weight: false
sample_during_evaluation: false

# time series vib
is_ensemble: False # always false

# gp_vib
kernel: cauchy
sigma: 0.7
length_scale: 1
kernel_scales: 1