defaults:
  - _self_
  - datamodule: uea
  - model: gpvib_e_inception_d_flatten
  - trainer: uea
  - logger: tensorboard
  - callbacks: uea
  - hydra: default
  - debug:
  - paths: default
  - metrics: uea
  - extras: default

seed:
mode: eval
optimized_metric: ${metrics.optimize}

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
ckpt_path:

# name of the run, should be used along with experiment mode
datamodule_name: uea
model_name: gp_vib
num_runs: 2
dataset_name:



