_target_: src.models.basics.gpvib.GPVIB
_partial_: True

defaults:
  - tsc_default.yaml

timeseries_encoder:
  _target_: src.models.encoders.BlockTimeSeriesDataEncoder
  _partial_: True
  input_size: -1
  ts_embedding_size: -1
  n_cnn_layers: -1
  out_channels_1: -1
  out_channels_2: -1
  out_channels_3: -1
  out_channels_4: -1
  kernel_size_1: -1
  kernel_size_2: -1
  kernel_size_3: -1
  kernel_size_4: -1
  dropout_1: -1
  dropout_2: -1
  dropout_3: -1
  dropout_4: -1
  time_series_hidden_1: 400
  time_series_hidden_2: -1
  time_series_hidden_3: -1
  hidden_size_1: -1
  hidden_size_2: -1
  hidden_size_3: -1
  timeseries_size: -1
  encoding_size: 8

encoder:
  _target_: src.models.encoders.BandedJointEncoder
  _partial_: True
  precision_activation:
    _target_: torch.nn.Softmax
  encoding_size: ${model.timeseries_encoder.encoding_size}

decoder:
  _target_: src.models.decoders.FlattenMultinomialDecoder
  _partial_: True
  z_dim: ${model.timeseries_encoder.encoding_size}
  hidden_size_1: 64
  hidden_size_2: -1
  hidden_size_3: -1
  num_samples: ${model.num_samples}
  output_size: ${model.num_classes}
