_target_: src.datasets.tsc.tsc.TimeSeriesClassification
_partial_: true

download_dir: ${paths.data_dir}/tsc/ucr
download_url: https://www.timeseriesclassification.com/aeon-toolkit/Archives/Univariate2018_ts.zip
file_name: Univariate2018_ts.zip
batch_size: 64
num_workers: 1
dataset_name:



